version: 2
jobs:
  build:
    docker:
      - image: polyglotted/rubypy
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            pip install awscli
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
      - run:
          name: Deploy
          command: |
            /bin/bash publish.sh
