version: 2
jobs:
  build:
    docker:
      - image: polyglotted/rubypy:1
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            sudo apt-get install python3-pip
            pip install awscli
            gem install jekyll
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
