version: 2
jobs:
  build:
    docker:
      - image: lambci/lambda:build-python3.6
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            pip install awscli
            gem install jekyll
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
