version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli
            gem install jekyll
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
