version: 2
jobs:
  build:
    docker:
      - image: polyglotted/rubypy:1
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            gem install jekyll
            apt-get install python-pip python-dev build-essential -y
            pip install awscli
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
