version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            pip install awscli
            gem install jekyll
      - run:
          name: Build and serve
          command: |
            jekyll serve --detach && curl "http://localhost:4000"
